name: DS4Vita

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake build-essential python3-pip curl

    - name: Install vitasdk
      run: |
        pip3 install --user vitasdk-installer
        ~/.local/bin/vitasdk-installer install
        echo "export VITASDK=$HOME/vitasdk" >> $GITHUB_ENV
        echo "export PATH=$HOME/vitasdk/bin:$PATH" >> $GITHUB_ENV

    - name: Build ds4vita
      run: |
        mkdir build
        cd build
        cmake ..
        make
