name: DS4Vita

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
      env:
        VITASDK: /usr/local/vitasdk
        PATH: /usr/local/vitasdk/bin:${{ env.PATH }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get install -y make git-core cmake build-essential python3-pip curl
        
    - name: Install vitasdk
      run: |
        git clone https://github.com/vitasdk/vdpm
        cd vdpm
        sudo ./bootstrap-vitasdk.sh
        sudo export VITASDK=/usr/local/vitasdk
        sudo export PATH=$VITASDK/bin:$PATH
        sudo ./install-all.sh
        
    - name: Build ds4vita
      run: |
        mkdir build
        cd build
        cmake ..
        make
