name: DS4Vita

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get install -y make git-core cmake build-essential python3-pip curl

    - name: Install vitasdk
      run: |
        git clone https://github.com/vitasdk/vdpm
        cd vdpm
        sudo ./bootstrap-vitasdk.sh
        ./install-all.sh

    - name: Set VITASDK environment
      run: |
        echo "export VITASDK=/usr/local/vitasdk" >> $GITHUB_ENV
        echo "/usr/local/vitasdk/bin" >> $GITHUB_PATH
        
    - name: Build ds4vita
      run: |
        mkdir build
        cd build
        cmake ..
        make
