name: DS4Vita

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential && git clone https://github.com/vitasdk/vdpm && cd vdpm && ./bootstrap-vitasdk.sh && ./install-all.sh

    - name: Build project
      run: |
        mkdir -p build
        cd build
        cmake ..
        make

    - name: Package artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: build/