name: DS34Vita

on:
  push:
    branches: [ all ]
  pull_request:
    branches: [ all ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get install -y make git-core cmake build-essential python3-pip curl
        
    - name: Install vitasdk
      run: |
        git clone https://github.com/vitasdk/vdpm
        cd vdpm
        ./bootstrap-vitasdk.sh
        ./install-all.sh

      env:
        VITASDK: /usr/local/vitasdk
        
    - name: Build ds34vita
      run: |
        mkdir build
        cd build
        cmake ..
        make

      env:
        VITASDK: /usr/local/vitasdk

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: vitacontrol
        path: build/ds34vita.skprx
        
